@startuml inline_umlgraph_1.svg
class FlowController {
    create()
    getAll()
    delete()
}

FlowController --> Flow : Utilizes

note right of FlowController
Responsibilities:
- Can retrieve multiple flows
- Can create new Flow
- Can delete one flow

 Collaborators:
 - Flow
end note
@enduml
@startuml inline_umlgraph_2.svg
class Flow{
    setName()
    getName()
    setId()
    getId()
}
@enduml
