@startuml inline_umlgraph_1.svg
class FlowController {
    create()
    getAll()
    delete()
}

FlowController --> Flow : Utilizes

note right of FlowController
Responsibilities:
- Can retrieve multiple flows
- Can create new Flow
- Can delete one flow

 Collaborators:
 - Flow
end note
@enduml
@startuml inline_umlgraph_2.svg
class CaptureFile {
- getId()
- setId()
- getApplication()
- setApplication()
- getCategory()
- setCategory()
- getSource()
- setSource()
- getIndex()
- setIndex()
- getRetentionTime()
- setRetentionTime()
- getTag()
- setTag()
- getFlow()
- setFlow()
- getProtocal()
- setProtocal()
- getTagPath()
- setTagPath()
- getCapturePath()
- setCapturePath()
- getFileProcessingTypeId()
- setFileProcessingTypeId()
- getType()
- setType()

 }
note right of CaptureFile
Responsibilities:
- Set/get id
- Set/get application
- Set/get category
- Set/get sourcetype
- Set/get index
- Set/get retentionTime
- Set/get tag
- Set/get flow
- Set/get protocol
- Set/get tagPath
- Set/get capturePath
- Set/get fileProcessingTypeId
- Set/get type

end note
@enduml
@startuml inline_umlgraph_3.svg
class Flow{
    setName()
    getName()
    setId()
    getId()
}
@enduml
