@startuml inline_umlgraph_1.svg
class CaptureFileController {
 create()
 get()
 getAll()
 delete()
}

CaptureFileController --> CaptureFile : Utilizes

note right of CaptureFileController
Responsibilities:
 - Create CaptureFile
 - Get CaptureFile
 - Get All CaptureFiles
 - Delete CaptureFile

Collaborators:
- CaptureFile

end note
@enduml
@startuml inline_umlgraph_2.svg
class FlowController {
    create()
    getAll()
    delete()
}

FlowController --> Flow : Utilizes

note right of FlowController
Responsibilities:
- Can retrieve multiple Flows
- Can create new Flow
- Can delete one Flow

 Collaborators:
 - Flow
end note
@enduml
@startuml inline_umlgraph_3.svg
class CaptureDefinition{
    setId()
    getId()
    setTag()
    getTag()
    setSourcetype()
    getSourcetype()
    setApplication()
    getApplication()
    setCaptureIndex()
    getCaptureIndex()
}
@enduml
@startuml inline_umlgraph_4.svg
class CaptureFile {
- getId()
- setId()
- getApplication()
- setApplication()
- getCategory()
- setCategory()
- getSource()
- setSource()
- getIndex()
- setIndex()
- getRetentionTime()
- setRetentionTime()
- getTag()
- setTag()
- getFlow()
- setFlow()
- getProtocal()
- setProtocal()
- getTagPath()
- setTagPath()
- getCapturePath()
- setCapturePath()
- getFileProcessingTypeId()
- setFileProcessingTypeId()
- getType()
- setType()

 }
note right of CaptureFile
Responsibilities:
- Set/get id
- Set/get application
- Set/get category
- Set/get sourcetype
- Set/get index
- Set/get retentionTime
- Set/get tag
- Set/get flow
- Set/get protocol
- Set/get tagPath
- Set/get capturePath
- Set/get fileProcessingTypeId
- Set/get type

end note
@enduml
@startuml inline_umlgraph_5.svg
Class CaptureGroup {
    - getTag()
    - setTag()
    - getCapture_def_group_name()
    - setCapture_def_group_name()
    - getCapture_definition_id()
    - setCapture_definition_id()
    - getId()
    - setId()
    - getCapture_group_type()
    - setCapture_group_type()
}

note right of CaptureGroup
Responsibilities:
    - can get/set Tag
    - can get/set Capture definition group name
    - can get/set Capture definition Id
    - can get/set Id
    - can get/set Capture group type

end note
@enduml
@startuml inline_umlgraph_6.svg
class CaptureDefinition{
    setCaptureId()
    getCaptureId()
    setCaptureMetaKey()
    getCaptureMetaKey()
    setCaptureMetaValue()
    getCaptureMetaValue()
}
@enduml
@startuml inline_umlgraph_7.svg
class CaptureRelp {
    setId()
    getId()
    setTag()
    getTag()
    setApplication()
    getApplication()
    setIndex()
    getIndex()
    setRetentionTime()
    getRetentionTime()
    setSourceType()
    getSourceType()
    setCategory()
    getCategory()
    setFlow()
    getFlow()
    setProtocol()
    getProtocol()
    setType()
    getType()
}
@enduml
@startuml inline_umlgraph_8.svg
class CaptureDefinition{
    setStorageId()
    getStorageId()
    setCaptureId()
    getCaptureId()
    setStorageName()
    getStorageName()
}
@enduml
@startuml inline_umlgraph_9.svg
class Flow{
    setName()
    getName()
    setId()
    getId()
}
@enduml
